micronaut:
  http:
    client:
      read-timeout: 30s
    services:
      api-client:
        url: http://api.ravishrajput.com
        api-auth: Basic ZHVtbXlSZXN0QXBpOmNzYjJqOUFrNlhqZEVQNVlJZT0=
        endpoint: /v1/user
        endpoint-flight: /v1/flight/getAllFlights
        endpoint-fareDetails: /v1/flight/fareDetails
        endpoint-airlines: /v1/flight/airlines
        endpoint-cities: /v1/flight/cities
graphql:
  graphiql:
    enabled: true
basic-auth:
  username: ravishrajput-bff
  password: dummyPwd